version: '3.8'

services:
  wework-bot:
    build: .
    container_name: wework-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TZ=Asia/Shanghai
      - ENABLE_CRON=true
      - CRON_SCHEDULE=0 10 * * 1-5
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  logs:
    driver: local